site_name: openKARST Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples.md
  - Parameter Reference: parameter_reference.md
  - Contributing: contributing.md
  - API Reference:
      - openkarst: reference/openkarst.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature: false
            show_submodules: true
            group_by_category: true
            show_if_no_docstring: true
            docstring_style: google
            render_module_header: true
            show_root_full_path: false
            heading_level: 3
            filters: []

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
theme:
  name: material
  features:
    - content.tabs.link
  

extra:
  version: "0.3.0"
  paths:
    - src