[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openkarst"
version = "0.3.0"
description = "A package for simulating flow in karst conduit networks"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Jannes Kordilla", email = "jannes.kordilla@csic.es" }
]
urls = { "Homepage" = "https://github.com/ERC-Karst/openkarst" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research"
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "networkx",
    "openpnm",
    "pandas",
    "dash",
    "plotly",
    "imageio-ffmpeg",
    "pyvista",
    "termcolor"
]

[project.optional-dependencies]
dev = [
    "mkdocs",
    "mkdocs-material",
    "pytest"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.setuptools.package-data]
"openkarst" = ["cave_data/*/*.csv"]
"openkarst.visualization" = ["assets/*.png"]
